name: 'Cntainer action'
description: 'Memory check'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  MyOutput: # id of output
    description: 'Total memory'
runs:
  using: 'docker'
  image: 'Dockerfile'
#  args:
#    - ${{ inputs.who-to-greet }}
